#!/usr/bin/env bun

/**
 * Full release pipeline:
 *   1. bumpp — interactive version bump + changelog + commit (no tag, no push)
 *   2. GPG-signed annotated tag with changelog body
 *   3. Push commit + tag to remote
 *
 * Usage:
 *   bun run release          # Interactive (bumpp prompts for version)
 *   bun run release --dry    # Dry run — stop after bumpp, no tag or push
 *
 * Tag message template:
 *   Release v{version}
 *
 *   ### Features
 *   - feat description
 *   ### Bug Fixes
 *   - fix description
 *   ...
 *
 * The changelog body is auto-generated by git-cliff from commits since the
 * previous tag. This makes `git show v{version}` a self-contained release note.
 */

import { execSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join } from "node:path";

function run(cmd: string, opts?: { stdio?: "inherit" | "pipe" }): string {
  const result = execSync(cmd, {
    encoding: "utf8",
    stdio: opts?.stdio ?? "inherit",
  });
  return typeof result === "string" ? result.trim() : "";
}

const isDry = process.argv.includes("--dry");

// ─── Step 1: bumpp (version bump + changelog + commit) ───────────────────

console.log("Running bumpp...\n");
run("bunx bumpp");

// Read the version bumpp wrote to package.json
const pkg = JSON.parse(run("cat package.json", { stdio: "pipe" }));
const version: string = pkg.version;
const tag = `v${version}`;

console.log(`\nVersion: ${version}`);

if (isDry) {
  console.log(`[DRY RUN] Would create signed tag ${tag} and push.`);
  process.exit(0);
}

// ─── Step 2: Build tag message from git-cliff ──────────────────────────

let changelog = "";
try {
  changelog = run(`git cliff --tag ${tag} --unreleased --strip all`, { stdio: "pipe" });
} catch {
  // No unreleased commits or git-cliff not available — proceed without body
}

const lines = [`Release ${tag}`];
if (changelog) {
  lines.push("", changelog);
}
const message = lines.join("\n");

// ─── Step 3: Create signed annotated tag ───────────────────────────────

// Remove stale tag if bumpp somehow created one (shouldn't with tag: false)
try {
  const existing = run(`git cat-file -t ${tag}`, { stdio: "pipe" });
  if (existing === "commit") {
    run(`git tag -d ${tag}`);
  } else if (existing === "tag") {
    console.log(`Tag ${tag} already exists. Skipping tag creation.`);
    process.exit(0);
  }
} catch {
  // Tag doesn't exist — expected path
}

const msgFile = join(tmpdir(), `release-tag-msg-${tag}.txt`);
await Bun.write(msgFile, message);

run(`git tag -s ${tag} -F "${msgFile}"`);
console.log(`Created signed tag: ${tag}`);

// ─── Step 4: Push ────────────────────────────────────────────────────────

run("git push");
run(`git push origin ${tag}`);
console.log(`Pushed ${tag} to remote — release.yml will trigger npm publish.`);
